# permissions for end users to view kruizes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kruize-operator
    app.kubernetes.io/managed-by: kustomize
  name: kruize-viewer-role
rules:
- apiGroups:
  - kruize.io
  resources:
  - kruizes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kruize.io
  resources:
  - kruizes/status
  verbs:
  - get
