apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kruize-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kruize is the Schema for the kruizes API
      displayName: Kruize
      kind: Kruize
      name: kruizes.kruize.io
      version: v1alpha1
  description: Resource optimization tool for Kubernetes workloads
  displayName: Kruize Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - resource optmization
  - right-sizing recommendations
  - performance
  - cost
  - namespace recommendations
  - acclerator recommendations autoscaling
  links:
  - name: Kruize Operator
    url: https://kruize-operator.domain
  maturity: alpha
  provider:
    name: Kruize
  version: 0.0.0
